package it.water.assettag.service;

import it.water.assettag.api.*;
import it.water.assettag.model.*;
import it.water.core.api.permission.SecurityContext;
import it.water.core.api.registry.ComponentRegistry;
import it.water.core.interceptors.annotations.*;
import it.water.repository.service.BaseEntityServiceImpl;
import lombok.*;


/**
 * @Generated by Water Generator
 * Service Api Class for AssetTag entity.
 *
 */
@FrameworkComponent
public class AssetTagServiceImpl extends BaseEntityServiceImpl<AssetTag> implements AssetTagApi {

    @Inject
    @Getter
    @Setter
    private AssetTagSystemApi systemService;

    @Inject
    @Getter
    @Setter
    private ComponentRegistry componentRegistry;

    public AssetTagServiceImpl() {
        
        super(AssetTag.class);
    }
    
    //todo: add custom logic here...
    //use getLog to retrieve Logger instance automatically instantiated for this class
}
