package it.water.assettag.service;

import it.water.assettag.api.AssetTagRepository;
import it.water.assettag.api.AssetTagSystemApi;
import it.water.assettag.model.AssetTag;
import it.water.assettag.model.AssetTagResource;
import it.water.core.api.asset.AssetTagManager;
import it.water.core.api.model.PaginableResult;
import it.water.core.api.registry.filter.ComponentFilterBuilder;
import it.water.core.interceptors.annotations.*;

import it.water.repository.service.BaseEntitySystemServiceImpl;

import lombok.*;

import java.util.ArrayList;
import java.util.List;


/**
 * @Generated by Water Generator
 * System Service Api Class for AssetTag entity.
 * Implements both AssetTagSystemApi (entity CRUD) and AssetTagManager (cross-module management).
 * This follows the same pattern as UserSystemServiceImpl which implements UserSystemApi and UserManager.
 */
@FrameworkComponent
public class AssetTagSystemServiceImpl extends BaseEntitySystemServiceImpl<AssetTag>
        implements AssetTagSystemApi, AssetTagManager {

    @Inject
    @Getter
    @Setter
    private AssetTagRepository repository;

    @Inject
    @Setter
    private ComponentFilterBuilder componentFilterBuilder;

    public AssetTagSystemServiceImpl() {
        super(AssetTag.class);
    }

    /**
     * Find an AssetTagResource by its parameters
     */
    @Override
    public it.water.core.api.model.AssetTagResource findAssetTagResource(String resourceName, long resourceId, long tagId) {
        getLog().debug("Finding AssetTagResource for resource: {} - {} in tag: {}",
                resourceName, resourceId, tagId);
        AssetTag tag = this.find(tagId);
        if (tag != null && tag.getResources() != null) {
            return tag.getResources().stream()
                    .filter(r -> r.getResourceName().equals(resourceName) && r.getResourceId() == resourceId)
                    .findFirst()
                    .orElse(null);
        }
        return null;
    }

    /**
     * Add a tag to a resource
     */
    @Override
    public void addAssetTag(String resourceName, long resourceId, long tagId) {
        getLog().debug("Adding AssetTag {} to resource: {} - {}", tagId, resourceName, resourceId);
        AssetTag tag = this.find(tagId);
        if (tag != null) {
            // Check if association already exists
            if (findAssetTagResource(resourceName, resourceId, tagId) == null) {
                AssetTagResource atr = new AssetTagResource(resourceName, resourceId, tag);
                tag.getResources().add(atr);
                this.update(tag);
            }
        }
    }

    /**
     * Add multiple tags to a resource
     */
    @Override
    public void addAssetTags(String resourceName, long resourceId, long[] tagsId) {
        getLog().debug("Adding {} tags to resource: {} - {}", tagsId.length, resourceName, resourceId);
        for (long tagId : tagsId) {
            addAssetTag(resourceName, resourceId, tagId);
        }
    }

    /**
     * Find all tags associated with a resource
     */
    @Override
    public long[] findAssetTags(String resourceName, long resourceId) {
        getLog().debug("Finding tags for resource: {} - {}", resourceName, resourceId);
        List<Long> tagIds = new ArrayList<>();

        // Get all tags and filter by resource
        PaginableResult<AssetTag> allTags = this.findAll(null, -1, -1, null);
        for (AssetTag tag : allTags.getResults()) {
            if (tag.getResources() != null) {
                boolean hasResource = tag.getResources().stream()
                        .anyMatch(r -> r.getResourceName().equals(resourceName) && r.getResourceId() == resourceId);
                if (hasResource) {
                    tagIds.add(tag.getId());
                }
            }
        }

        return tagIds.stream().mapToLong(Long::longValue).toArray();
    }

    /**
     * Remove a tag from a resource
     */
    @Override
    public void removeAssetTag(String resourceName, long resourceId, long tagId) {
        getLog().debug("Removing AssetTag {} from resource: {} - {}", tagId, resourceName, resourceId);
        AssetTag tag = this.find(tagId);
        if (tag != null && tag.getResources() != null) {
            // Find and remove the resource from the collection
            AssetTagResource toRemove = null;
            for (AssetTagResource atr : tag.getResources()) {
                if (atr.getResourceName().equals(resourceName) && atr.getResourceId() == resourceId) {
                    toRemove = atr;
                    break;
                }
            }
            if (toRemove != null) {
                tag.getResources().remove(toRemove);
                this.update(tag);
            }
        }
    }

    /**
     * Remove multiple tags from a resource
     */
    @Override
    public void removeAssetTags(String resourceName, long resourceId, long[] tagsId) {
        getLog().debug("Removing {} tags from resource: {} - {}", tagsId.length, resourceName, resourceId);
        for (long tagId : tagsId) {
            removeAssetTag(resourceName, resourceId, tagId);
        }
    }
}
