
package it.water.assettag.service.rest.spring;

import it.water.assettag.service.rest.AssetTagRestControllerImpl;
import it.water.core.api.model.*;
import it.water.core.api.repository.*;
import it.water.core.api.repository.query.*;
import it.water.assettag.api.*;
import it.water.assettag.model.*;
import org.springframework.web.bind.annotation.RestController;


/**
 * @Generated by Water Generator
 * Rest Api Class for AssetTag entity. It just overrides method invoking super in order to let spring find web methods.
 */
@RestController
public class AssetTagSpringRestControllerImpl extends AssetTagRestControllerImpl implements AssetTagSpringRestApi {
        @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public AssetTag save(AssetTag entity) {
        return super.save(entity);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public AssetTag update(AssetTag entity) {
        return super.update(entity);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public void remove(long id) {
        super.remove(id);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public AssetTag find(long id) {
        return super.find(id);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public PaginableResult<AssetTag> findAll(Integer delta, Integer page, Query filter, QueryOrder order) {
        return super.findAll(delta, page, filter, order);
    }

    @Override
    @SuppressWarnings("java:S1185") //disabling sonar because spring needs to override this method
    public PaginableResult<AssetTag> findAll() {
        return super.findAll();
    }
    }
