
package it.water.assettag.service.rest;

import it.water.assettag.api.*;
import it.water.assettag.api.rest.*;
import it.water.assettag.model.*;

import it.water.core.api.service.BaseEntityApi;
import it.water.service.rest.persistence.BaseEntityRestApi;
import it.water.core.api.service.rest.FrameworkRestController;
import it.water.core.interceptors.annotations.*;


import lombok.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * @Generated by Water Generator
 * Rest Api Class for AssetTag entity.
 *
 */
@FrameworkRestController(referredRestApi = AssetTagRestApi.class)
public class AssetTagRestControllerImpl extends BaseEntityRestApi<AssetTag> implements AssetTagRestApi {
    @SuppressWarnings("java:S1068") //still mantain the variable even if not used
    private static Logger log = LoggerFactory.getLogger(AssetTagRestControllerImpl.class.getName());
    
    @Inject
    @Setter
    private AssetTagApi assetTagApi;
    @Override
    protected BaseEntityApi<AssetTag> getEntityService() {
        return assetTagApi;
    }
    //All CRUD methods are already exposed by AssetTagRestApi interface with JAXRS Annotatiosn
    //if you need to check which methods are exposed please go to it.water.assettag.api.rest.AssetTag

    //todo add custom exposed methods or override CRUD operations
    //ATTENTION: use always AssetTagApi in order to ensure the user is requesting operations has the right privileges to do it

}
