package it.water.assettag.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import it.water.repository.jpa.model.AbstractJpaExpandableEntity;

import java.util.HashSet;
import java.util.Set;
import it.water.core.api.service.rest.WaterJsonView;
import it.water.core.api.entity.owned.OwnedResource;
import it.water.core.api.permission.*;
import it.water.core.permission.action.CrudActions;
import it.water.core.permission.annotations.AccessControl;
import it.water.core.permission.annotations.DefaultRoleAccess;
import lombok.*;
import it.water.core.validation.annotations.*;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;

import com.fasterxml.jackson.annotation.JsonView;


/**
 * @Generated by Water Generator
 * AssetTag Entity Class.
 *
 * Represents a tag that can be associated with any entity in the system.
 * Tags are used to categorize and organize resources.
 */
@Entity
@Table(uniqueConstraints = @UniqueConstraint(columnNames = {"name", "ownerUserId"}))
@Access(AccessType.FIELD)
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@RequiredArgsConstructor
@Getter
@Setter(AccessLevel.PROTECTED)
@ToString(exclude = {"resources"})
@EqualsAndHashCode(of = {"name"}, callSuper = true)
@AccessControl(availableActions = {CrudActions.SAVE, CrudActions.UPDATE, CrudActions.FIND, CrudActions.FIND_ALL, CrudActions.REMOVE},
        rolesPermissions = {
                @DefaultRoleAccess(roleName = AssetTag.DEFAULT_MANAGER_ROLE, actions = {CrudActions.SAVE, CrudActions.UPDATE, CrudActions.FIND, CrudActions.FIND_ALL, CrudActions.REMOVE}),
                @DefaultRoleAccess(roleName = AssetTag.DEFAULT_VIEWER_ROLE, actions = {CrudActions.FIND, CrudActions.FIND_ALL}),
                @DefaultRoleAccess(roleName = AssetTag.DEFAULT_EDITOR_ROLE, actions = {CrudActions.SAVE, CrudActions.UPDATE, CrudActions.FIND, CrudActions.FIND_ALL})
        })
public class AssetTag extends AbstractJpaExpandableEntity implements ProtectedEntity, OwnedResource {

    public static final String DEFAULT_MANAGER_ROLE = "AssetTagManager";
    public static final String DEFAULT_VIEWER_ROLE = "AssetTagViewer";
    public static final String DEFAULT_EDITOR_ROLE = "AssetTagEditor";

    /**
     * Tag name - required, unique per owner
     */
    @NoMalitiusCode
    @NotNull
    @NotEmpty
    @NotNullOnPersist
    @NonNull
    @Size(max = 255)
    @Setter
    @JsonView(WaterJsonView.Extended.class)
    private String name;

    /**
     * Tag description - optional
     */
    @NoMalitiusCode
    @Size(max = 255)
    @Setter
    @JsonView(WaterJsonView.Extended.class)
    private String description;

    /**
     * Tag color (hex format, e.g., #FF0000) - optional
     */
    @NoMalitiusCode
    @Size(min = 3, max = 7)
    @Setter
    @JsonView(WaterJsonView.Extended.class)
    private String color;

    /**
     * Owner user id of the entity
     */
    @Setter
    @NonNull
    @JsonIgnore
    @JsonView({WaterJsonView.Extended.class})
    private Long ownerUserId;

    /**
     * Resources associated with this tag
     */
    @JsonIgnore
    @OneToMany(mappedBy = "tag", orphanRemoval = true, cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private Set<AssetTagResource> resources = new HashSet<>();
}