package it.water.assettag.api;

import it.water.core.api.repository.BaseRepository;
import it.water.core.interceptors.annotations.*;
import it.water.assettag.model.AssetTag;

/**
 * @Generated by Water Generator
 * Interface component for AssetTag Repository.
 * It is used for CRUD operations, and to interact with the persistence layer.
 *
 */
public interface AssetTagRepository extends BaseRepository<AssetTag> {
	
}
