package it.water.assettag.api;

import it.water.core.api.service.BaseEntitySystemApi;

import it.water.assettag.model.AssetTag;

/**
 * @Generated by Water Generator
 * This interface defines the internally exposed methods for the entity and allows interaction with it bypassing permission system.
 * The main goals of AssetTagSystemApi is to validate the entity and pass it to the persistence layer.
 */
public interface AssetTagSystemApi extends BaseEntitySystemApi<AssetTag> {

}