package it.water.assettag.api;

import it.water.core.api.service.BaseEntityApi;

import it.water.assettag.model.AssetTag;

/**
 * @Generated by Water Generator
 * This interface defines the externally exposed methods for the entity and allows interaction with it through a permission system.
 *
 */
public interface AssetTagApi extends BaseEntityApi<AssetTag> {

}